name: docs

on:
  release:
    types: [ released ]
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch origin gh-pages --depth=1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install
        run: |
          pip install -e .
          pip install -r docs/requirements.txt

      - name: Create the storage
        run: |
          mkdir -p ~/.config/amid/ && cp tests/assets/.bev.yml ~/.config/amid/.bev.yml
          amid init

      - name: Generate the missing pages
        run: |
          cd docs && python fill_docs.py

      # release
      - id: get_version
        if: ${{ github.ref == 'refs/heads/master' }}
        name: Get the release version
        uses: battila7/get-version-action@v2

      - name: Deploy the docs
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          PYTHONPATH=$PYTHONPATH:./docs mike deploy ${{ steps.get_version.outputs.version-without-v }} latest --push --update-aliases

      # dev
      - name: Deploy the docs
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          PYTHONPATH=$PYTHONPATH:./docs mike deploy dev --push
