name: docs

on: [ pull_request ]
#on:
#  release:
#    types: [ released ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install
        run: |
          pip install -e .
          pip install -r docs/requirements.txt

      - name: Create the storage
        run: |
          mkdir -p ~/.config/amid/ && cp tests/assets/.bev.yml ~/.config/amid/.bev.yml
          amid init

      - name: Deploy the docs
        run: PYTHONPATH=$PYTHONPATH:./docs mkdocs gh-deploy --force
